### ISSUE TITLE
"icon.ico" relative path?

### ISSUE THREAD

**Issue by albertmeronyo** [mhbeals/nisaba#13]
So the lines that load the icon bitmap are harmless on Windows and MacOS, but Tk on Linux will crash at e.g.

```
root.iconbitmap('icon.ico')
```

Maybe we should use `Path` there too, or `os.path.join()`?

**Comment by mhbeals** [comment]
This may be a problem with the file formats rather than the path (https://stackoverflow.com/questions/20860325/python-3-tkinter-iconbitmap-error-in-ubuntu).   We may need to include a separate icon file for Linux or go to a mutually intelligible one.

I am going to add more icons as we go (for buttons, etc) so a separate assets directory would be sensible.

**Comment by mhbeals** [comment]
A fix has been implemented.  Test by @albertmeronyo requested.

**Comment by albertmeronyo** [comment]
With commit a4792820267d2e682b503e63599a6536473153d5 this works fine in MacOS and Windows, but still fails in Linux. Setting the icon on a `Tk()` object, like in [__main__.py] [here](https://github.com/mhbeals/nisaba/blob/master/nisaba/__main__.py#L40), seems to work; but on a `Toplevel()` object (like [here](https://github.com/mhbeals/nisaba/blob/master/nisaba/metadata_display.py#L165)) it fails with

```
  File "/home/amp/src/nisaba/nisaba/metadata_display.py", line 165, in database_metadata_viewer
    self.metadata_window.call('wm', 'iconphoto', self.metadata_window._w, logo)
AttributeError: 'Toplevel' object has no attribute 'call'
```

Maybe this is not so important for now as as a majority of users run Windows/MacOS?

**Comment by mhbeals** [comment]
I concur. Perhaps Linux users will just have to deal with the default icon.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
